// Matches the pre-filled greeting text generated by the demo portfolio
// landing page (frontend demo.html), e.g. "Hi, I'm Henry — Welcome to
// Henry's Real Estate demo!" — lets any channel's inbound handler capture
// the visitor's typed first name without needing a separate session/lookup
// mechanism. If the visitor edits the pre-filled text before sending, this
// simply won't match and personalization falls back to the channel's own
// profile name (if any) or a generic default.
const DEMO_GREETING_RE = /^hi,?\s*i'?m\s+([a-z][a-z'-]*)/i;

function capitalize(name) {
  return name.charAt(0).toUpperCase() + name.slice(1).toLowerCase();
}

function captureNameFromGreeting(text) {
  const match = (text || '').match(DEMO_GREETING_RE);
  return match ? capitalize(match[1].trim()) : null;
}

module.exports = { captureNameFromGreeting };
